### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Joohansson** [JZito/blockchain_visualizer#1]
Hi, amazing work! I made a fork of this and ported to Nano network for demo purpose.
https://github.com/joohansson/nanomusic

I saw a standard license is missing, would be great if there was one so I can add it too.
I hope it's ok I use it.

I have linked to this repo both from my repo and on the page itself (under about).

**Comment by JZito** [comment]
Wow, great work! I'm so happy to see someone utilizing this and I like your updates.

I appreciate the links, and I've added an MIT license for anyone else in the future.
